name: tests

on:
  push:
    branches:
    - "main"
  pull_request:

jobs:

  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
